<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<title>MSET-2025</title>';
echo '<link rel="icon" type="image/png" href="/assests/dsu.png">';
echo '<link rel="stylesheet" href="/styles.css">';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '<div class="navbar">';
echo '<div class="logo">';
echo '<img src="https://www.dsuniversity.ac.in/images/DSU_Logo.png" alt="University Logo">';
echo '</div>';
echo '<div class="navbar-left">';
echo '<h2>DHANALAKSHMI SRINIVASAN  UNIVERSITY</h2>';
echo '<p>Established Under The Tamil Nadu Private Universities Act, 2019</p>';
echo '<p>Tiruchirappalli - 621 112. Tamil Nadu, India.</p>';
echo '</div>';
echo '<div class="nav-links">';
echo '<a href="#home">Home</a>';
echo '<a href="#about">About</a>';
echo '<a href="#topics">Conference Topics</a>';
echo '<a href="#key-dates">Key Dates</a>';
echo '<a href="#submissions">Submissions</a>';
echo '<a href="#registration">Registration</a>';
echo '<a href="#contact">Contact Us</a>';
echo '</div>';
echo '</div>';
echo '<hr>';
echo '<div class="marquee-alternate">';
echo '<a href="https://example.com" target="_blank">🎉 ABSTRACT SUBMISSION DEADLINE : [ 28 / 02 / 25] </a>';
echo '</div>';
echo '';
echo '';
echo '<section id="home">';
echo '<div class="banner">';
echo '<!--image-->';
echo '<a href="https://dsuniversity.ac.in" target="_blank">';
echo '<img src="/assests/mset.png" alt="MSET 2025 Conference Banner" style="width: 100%; height: auto;">';
echo '</a>';
echo '</div>';
echo '</section>';
echo '';
echo '<section class="about">';
echo '<h1>We cordially invite you to join us at <span>MSET2025! </span><br>';
echo 'April, 2025 | Trichy,Tamil Nadu</h1>';
echo '<p>';
echo 'Join us at the MSET2025 on APRIL 2025 in Trichy,Tamil Nadu This event focuses on';
echo '<strong>"FIRST INTERNATIONAL CONFERENCE ON MULTIDISCIPLINARY SOLUTIONS FOR EMERGING TRENDS"</strong> Engage with experts,';
echo 'policymakers, and professionals from around the world to discuss and develop innovative solutions';
echo 'to challenges surrounding pandemics. Don't miss this opportunity to network, share knowledge,';
echo 'and contribute to global health resilience. Register now and be part of the conversation that';
echo 'shapes the future of global healthcare and humanitarian efforts.';
echo '</p>';
echo '</section>';
echo '<div  class="logo2">';
echo '<img src="/assests/logo.png">';
echo '</div>';
echo '<hr>';
echo '<section id="about">';
echo '<div class="about-container">';
echo '<div class="about-section">';
echo '<div class="about-text">';
echo '<h2>About Us</h2>';
echo '<p>The Dhanalakshmi Srinivasan University (DSU) has been established under the Tamil Nadu Private Universities Act, 2019, located in Tiruchirappalli, Tamil Nadu, India.';
echo 'Uniqueness of DSU lies in its multi-disciplinary nature in offering a wide range of academic programmes encompassing medicine and engineering. Our motto is "education';
echo 'for the real world" with dedication and commitment towards nurturing the future generation. Green ambience with state-of-the-art infrastructure along with top-class';
echo 'faculty aims to serve the need of national and international students.</p>';
echo '</div>';
echo '<div class="about-images">';
echo '<img src="https://dsuniversity.ac.in/infra/camp1.jpg" alt="Campus View">';
echo '<img src="https://th.bing.com/th/id/OIP.XUhPNJHFjro82CRviOftewHaED?pid=ImgDet&w=474&h=259&rs=1" alt="Library">';
echo '<img src="https://www.dsuniversity.ac.in/images/learn4.jpg" alt="Lecture Hall">';
echo '<img src="https://www.dsuniversity.ac.in/infra/campus-img-05.jpg" alt="Research Lab">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="about-container">';
echo '<div class="about-section">';
echo '<div class="about-text">';
echo '<h2>About <strong>School of Engineering and Technology</strong></h2>';
echo '<p><span>School of Engineering and Technology (SET)</span> in DSU is a beacon of innovation and academic excellence, offering';
echo 'cutting-edge programs designed to shape the next generation of engineering leaders. SET has a range of 12 departments';
echo 'that include Electrical and Electronics Engineering, Mechanical Engineering, Agriculture Engineering, Electronics and';
echo 'Communication Engineering, Biomedical Engineering, Biotechnology, Computer Science Engineering, Information Technology,';
echo 'Artificial Intelligence and Date Structure, Artificial Intelligence and Machine Learning, Cyber Security and Internet';
echo 'of Things. With a strong emphasis on practical learning and research, SET equips students with the technical expertise,';
echo 'critical thinking abilities, and hands-on experience needed to excel in a competitive, technology-driven world. SET';
echo 'boasts a team of highly qualified and experienced Faculty who are dedicated to mentoring students and fostering a';
echo 'culture of academic rigor and innovation. State-of-the-art laboratories, well-equipped workshops, and modern computing';
echo 'facilities ensure that students have access to the latest tools and technologies to enhance their learning experience.';
echo 'In addition to academics, SET emphasizes holistic development by encouraging participation in technical clubs,';
echo 'competitions, and industry collaborations. </p>';
echo '</div>';
echo '<div class="about-images">';
echo '<img src="https://www.dsuniversity.ac.in/gallery/g5.jpg" alt="Campus View">';
echo '<img src="https://www.dsuniversity.ac.in/gallery/l2.jpg" alt="Library">';
echo '<img src="https://www.dsuniversity.ac.in/images/learn1.jpg" alt="Lecture Hall">';
echo '<img src="https://www.dsuniversity.ac.in/gallery/t1.jpg" alt="Research Lab">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<div class="quick-links">';
echo '<h2>Quick Links:</h2>';
echo '<a href="#topics" class="btn">Conference</a>';
echo '<a href="#key-dates" class="btn">Key Dates</a>';
echo '<a href="#registration" class="btn">Registration</a>';
echo '<a href="#contact" class="btn">Contact Us</a>';
echo '<a href="#accomadation" class="btn">Accomadation</a>';
echo '</div>';
echo '<section class="event-container">';
echo '<div class="event-text">';
echo '<h1>Your Participation Matters!</h1>';
echo '<p>Be a part of the Change the world needs today.</p>';
echo '<div class="event-details">';
echo '<img src="https://static.vecteezy.com/system/resources/previews/009/589/226/original/location-location-pin-location-icon-transparent-free-png.png" height="53px" >';
echo '<p><i class="fas fa-map-marker-alt"></i> Seminar Hall ,<br>Dhanalakshmi Srinivasan University';
echo 'Trichy</p>';
echo '<img src="/assests/calender.png" height="53px">';
echo '<p><i class="fas fa-calendar-alt"></i> April 2025</p>';
echo '</div>';
echo '<center><button class="register-btn">Spot Your Seat</button></center>';
echo '</div>';
echo '<div class="event-image">';
echo '<img src="/assests/image.png" alt="Event Speaker" height="70%">';
echo '</div>';
echo '</section>';
echo '<section class="invitation">';
echo '<h1>The conference <span class="highlight">MSET2025!</span> <br>';
echo '</h1></section>';
echo '<section class="invitation2">';
echo '<p>';
echo 'Join us at the MSET2025 on APRIL 2025 in Trichy,Tamil Nadu This event focuses on';
echo '<strong><span class="highlight">"FIRST INTERNATIONAL CONFERENCE ON MULTIDISCIPLINARY SOLUTIONS IN ENGINEERING & TECHNOLOGY."</span></strong> Engage with experts,';
echo 'School of Engineering and Technology (SET) proudly hosts a two day International Conference on Multidisciplinary Solutions in Engineering';
echo 'and Technology, MSET 2025 on 25th and 26th April 2025. The Conference is a premier platform for global academics, researchers, industry';
echo 'professionals, and students to converge and exchange cutting-edge ideas. This conference is dedicated to addressing complex challenges';
echo 'through innovative, multidisciplinary approaches that bridge diverse fields of engineering and technology. The conference brings together';
echo 'experts from various domains, including mechanical, electrical, computer science, electronics, science, humanities and emerging technologies';
echo 'such as artificial intelligence, cyber security, machine learning and IoT.  By fostering collaboration across disciplines, the conference';
echo 'aims to explore novel solutions to pressing societal and industrial challenges. Key highlights of MSET 2025 include keynote speeches by';
echo 'renowned international and national experts, technical paper presentations, and panel discussions. Participants gain valuable insights';
echo 'into global trends, groundbreaking research, and practical applications that shape the future of engineering and technology.';
echo 'The conference also provides an opportunity to showcase innovations, establish professional networks, and explore collaborative';
echo 'research and industry partnerships. Organized by SET at DSU, this event underscores the institution’s commitment to advancing';
echo 'knowledge, fostering innovation, and promoting global academic and industrial collaboration.';
echo '';
echo '';
echo '</p>';
echo '</section>';
echo '';
echo '<h1 class="top">WELCOME TO MSET2025!</h1>';
echo '<div class="countdown-container">';
echo '<center><p class="event-time">The event will start in</p>';
echo '<span id="days" class="time">00</span> Days :';
echo '<span id="hours"class="time">00</span> Hours :';
echo '<span id="minutes"class="time">00</span> Minutes :';
echo '<span id="seconds"class="time">00</span> Seconds </center>';
echo '</div>';
echo '';
echo '<section id="topics">';
echo '<div id="event-container" class="section">';
echo '<center><h2>Conference Topics</h2></center>';
echo '<div class="flip-card-container">';
echo '<div class="flip-card">';
echo '<div class="flip-card-inner">';
echo '<div class="flip-card-front">';
echo '<img src="/assests/tac.jpg" alt="Agriculture Icon">';
echo 'Technological Advancements & Challenges';
echo '</div>';
echo '<div class="flip-card-back">';
echo 'Explore the opportunities and challenges posed by AI, automation, and IoT in transforming industries while addressing growing cybersecurity threats that require robust data protection and privacy solutions.';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="flip-card">';
echo '<div class="flip-card-inner">';
echo '<div class="flip-card-front">';
echo '<img src="/assests/fs.jpg" alt="Agriculture Icon">';
echo 'Food Science & Biotechnology in Agriculture';
echo '</div>';
echo '<div class="flip-card-back">';
echo 'Development of genetically modified crops, sustainable farming practices, biotechnology in pest and disease control, improving crop yields and quality.';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="flip-card">';
echo '<div class="flip-card-inner">';
echo '<div class="flip-card-front">';
echo '<img src="/assests/ilaf.jpg ">';
echo 'Integrated Approaches in Life Science';
echo '</div>';
echo '<div class="flip-card-back">';
echo 'Interdisciplinary research in biology and medicine, advances in genomics and proteomics, innovative approaches to disease treatment, collaboration between academic and industry researchers.';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="flip-card">';
echo '<div class="flip-card-inner">';
echo '<div class="flip-card-front">';
echo '<img src="/assests/04.jpg">';
echo 'Sustainability & Climate Change';
echo '</div>';
echo '<div class="flip-card-back">';
echo 'Discuss how innovations in renewable energy, green technologies, and circular economies can mitigate climate change impacts such as rising temperatures, extreme weather events, and their effects on agriculture, water resources, and health.';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="flip-card">';
echo '<div class="flip-card-inner">';
echo '<div class="flip-card-front">';
echo '<img src="/assests/05.jpg">';
echo 'Collaborative Research in Pure and Applied Mathematics';
echo '</div>';
echo '<div class="flip-card-back">';
echo 'Advancements in theoretical mathematics, applications of mathematics in various industries, cross-disciplinary collaborations, impact of mathematical research on technology and society.';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="flip-card">';
echo '<div class="flip-card-inner">';
echo '<div class="flip-card-front">';
echo '<img src="/assests/06.jpg">';
echo 'Healthcare Disparities & Aging Population';
echo '</div>';
echo '<div class="flip-card-back">';
echo 'Addressing gaps in healthcare access in resource-limited regions, meeting the needs of the aging population, technological solutions like telemedicine and AI diagnostics, policy initiatives for equitable healthcare.';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="flip-card">';
echo '<div class="flip-card-inner">';
echo '<div class="flip-card-front">';
echo '<img src="/assests/07.jpg">';
echo 'Urbanization & Resource Management';
echo '</div>';
echo '<div class="flip-card-back">';
echo 'Delve into the pressures of rapid urbanization on water resources, exploring sustainable water management solutions for cities facing scarcity, pollution, and increased demand.';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="flip-card">';
echo '<div class="flip-card-inner">';
echo '<div class="flip-card-front">';
echo '<img src="/assests/08.jpg">';
echo 'Globalization & Economic Inequality';
echo '</div>';
echo '<div class="flip-card-back">';
echo 'Examine how globalization fosters innovation but also exacerbates economic inequality, and discuss policies to ensure a more equitable distribution of economic benefits.';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="flip-card">';
echo '<div class="flip-card-inner">';
echo '<div class="flip-card-front">';
echo '<img src="/assests/09.jpg">';
echo '📚 Education Access & Social Stability';
echo '</div>';
echo '<div class="flip-card-back">';
echo 'Focus on the role of education in driving societal change, addressing the impacts of unequal access to quality education on poverty, unemployment, and social unrest.';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="flip-card">';
echo '<div class="flip-card-inner">';
echo '<div class="flip-card-front">';
echo '<img src="/assests/10.jpg">';
echo 'Wellness Focus & Global Health Crises';
echo '</div>';
echo '<div class="flip-card-back">';
echo 'Analyze the increasing focus on health and wellness, while addressing the ongoing global health crises, including pandemics and chronic diseases, particularly in underserved regions.';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="flip-card">';
echo '<div class="flip-card-inner">';
echo '<div class="flip-card-front">';
echo '<img src="/assests/11.jpg">';
echo 'Migration & Geopolitical Instability';
echo '</div>';
echo '<div class="flip-card-back">';
echo 'Investigate the political and social challenges associated with migration driven by conflict, economic instability, and climate change, and explore solutions for integrating displaced populations.';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="flip-card">';
echo '<div class="flip-card-inner">';
echo '<div class="flip-card-front">';
echo '<img src="/assests/12.jpg">';
echo 'Incident Response and Threat Hunting';
echo '</div>';
echo '<div class="flip-card-back">';
echo 'Strategies for effective incident response, techniques for threat detection and hunting, tools and technologies for cybersecurity, collaboration and information sharing.';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section id="key-dates">';
echo '<div id="event-container" class="section">';
echo '<center><h2>Key Dates</h2></center>';
echo '<table class="registration-table">';
echo '<thead>';
echo '<tr>';
echo '<th>Event</th>';
echo '<th>Date</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody>';
echo '<tr>';
echo '<td>ABSTRACT SUBMISSION DEADLINE</td>';
echo '<td>FEBRUARY 28, 2025</td>';
echo '</tr>';
echo '<tr>';
echo '<td>FULL PAPER SUBMISSION</td>';
echo '<td>MARCH 31, 2025</td>';
echo '</tr>';
echo '<tr>';
echo '<td>ACCEPTANCE REVELATION</td>';
echo '<td>MARCH 5, 2025</td>';
echo '</tr>';
echo '<tr>';
echo '<td>REGISTRATION DEADLINE</td>';
echo '<td>FEBRUARY 28, 2025</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '</section>';
echo '';
echo '';
echo '<section id="registration">';
echo '<div id="event-container" class="section">';
echo '<center><h2>Registration</h2></center>';
echo '<table class="registration-table">';
echo '<thead>';
echo '<tr>';
echo '<th>Registration Fees: <br>(per paper)</th>';
echo '<th>Regular</th>';
echo '<th>Early bird</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody>';
echo '<tr>';
echo '<td>INTERNATIONAL</td>';
echo '<td>250 USD</td>';
echo '<td>200 USD</td>';
echo '</tr>';
echo '<tr>';
echo '<td>INDUSTRY</td>';
echo '<td>RS.10000</td>';
echo '<td>RS.7500</td>';
echo '</tr>';
echo '<tr>';
echo '<td>FACULTY</td>';
echo '<td>RS.7500</td>';
echo '<td>RS.3500</td>';
echo '</tr>';
echo '<tr>';
echo '<td>RESEARCH SCHOLAR</td>';
echo '<td>RS.5000</td>';
echo '<td>RS.3000</td>';
echo '</tr>';
echo '<tr>';
echo '<td>PG STUDENTS</td>';
echo '<td>RS.2000 (Max. Two authors)</td>';
echo '<td>RS.2000 (Max. Two authors)</td>';
echo '</tr>';
echo '<tr>';
echo '<td>UG STUDENTS</td>';
echo '<td>RS.1500 (Max. Four authors)</td>';
echo '<td>RS.1500 (Max. Four authors) </td>';
echo '</tr>';
echo '<tr>';
echo '<td>ATTENDEES</td>';
echo '<td>RS.750</td>';
echo '<td>RS.750</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</section>';
echo '';
echo '<div class="dropdown-item">';
echo '<input type="checkbox" id="why-attend-toggle" class="dropdown-toggle">';
echo '<label for="why-attend-toggle" class="dropdown-button">Why Should Attend <span class="arrow">&#9660;</span></label>';
echo '<div class="dropdown-content">';
echo '<p>Attending the MSET2025 conference will provide you with the opportunity to:</p>';
echo '<ul>';
echo '<li>Engage with experts and peers from around the world.</li>';
echo '<li>Discover innovative solutions to global challenges.</li>';
echo '<li>Network with policymakers, professionals, and academics.</li>';
echo '<li>Contribute to global health resilience and humanitarian efforts.</li>';
echo '<li>Gain insights into multidisciplinary approaches in engineering and technology.</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="dropdown-item">';
echo '<input type="checkbox" id="who-attend-toggle" class="dropdown-toggle">';
echo '<label for="who-attend-toggle" class="dropdown-button">Who Should Attend <span class="arrow">&#9660;</span></label>';
echo '<div class="dropdown-content">';
echo '<p>The MSET2025 conference is ideal for:</p>';
echo '<ul>';
echo '<li>Researchers and Academics</li>';
echo '<li>Industry Professionals</li>';
echo '<li>Policymakers and Government Officials</li>';
echo '<li>Healthcare Providers and Practitioners</li>';
echo '<li>Students and Young Professionals</li>';
echo '<li>Anyone interested in multidisciplinary solutions in engineering and technology</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '';
echo '<section id="submissions"><!-- Conference Features Container -->';
echo '<div class="conference-container">';
echo '<h2>Conference Features</h2>';
echo '';
echo '<div class="feature">';
echo '<h3>Keynote Addresses</h3>';
echo '<p>Renowned experts will deliver thought-provoking insights into the future of interdisciplinary problem-solving and the critical role of innovation in addressing global challenges.</p>';
echo '</div>';
echo '';
echo '<div class="feature">';
echo '<h3>Technical Sessions</h3>';
echo '<p>In-depth discussions will focus on the latest developments in technology, engineering, and social sciences that are reshaping the future of problem-solving.</p>';
echo '</div>';
echo '';
echo '<div class="feature">';
echo '<h3>Expert Panels</h3>';
echo '<p>Multidisciplinary panels will bring together thought leaders from diverse fields to discuss actionable solutions to complex global issues.</p>';
echo '</div>';
echo '';
echo '<div class="feature">';
echo '<h3>Collaborative Workshops</h3>';
echo '<p>Hands-on workshops will foster collaboration and creative thinking, encouraging participants to develop actionable solutions by integrating diverse perspectives.</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Publishing Details Container -->';
echo '<div class="publishing-container">';
echo '<img src="https://zh.library.ipm.edu.mo/sites/default/files/db-logo/db-logo-scopus.png" alt="Publishing Image">';
echo '';
echo '<div class="publishing-content">';
echo '<h2>Publishing Details</h2>';
echo '';
echo '<h3>Conference Proceedings</h3>';
echo '<p>Abstracts of all accepted and presented papers will be published in the conference proceedings, which will be assigned an ISBN (International Standard Book Number). This ensures that the work is formally documented and accessible.</p>';
echo '';
echo '<h3>Extended Papers in Journals</h3>';
echo '<p>Authors of selected papers will have the opportunity to extend their work and submit it for consideration in Scopus-indexed or UGC Care-listed journals. However, acceptance will depend on:</p>';
echo '';
echo '<ul>';
echo '<li><strong>Scope:</strong> The paper must align with the journal's thematic focus.</li>';
echo '<li><strong>Quality:</strong> The paper must meet the journal's academic and technical standards.</li>';
echo '<li><strong>Financial Requirements:</strong> Authors may need to pay additional publication fees, if applicable, as per the journal's policies.</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '';
echo '</section>';
echo '<section id="contact">';
echo '<div class="committee-section">';
echo '<center><h2>MSET2025 TEAM</h2></center>';
echo '<h3 class="chief-patrons-title">Chief Patrons</h3><br>';
echo '<div class="team-section">';
echo '';
echo '<div class="committee-member committee-layout">';
echo '<img src="https://www.dsuniversity.ac.in/images/chairman.png" alt="Shri. A. Srinivasan" class="image-container">';
echo '<div class="text-container">';
echo '<strong><span>Shri. A. Srinivasan</span></strong><br>';
echo 'Position: Founder-Chancellor<br>';
echo '';
echo '</div>';
echo '</div>';
echo '<div class="committee-member committee-layout">';
echo '<img src="https://www.dsuniversity.ac.in/img/staff/pro-chancellor.jpeg" alt="Mrs. Ananthalakshmi Kathiravan" class="image-container">';
echo '<div class="text-container">';
echo '<strong><span> Ananthalakshmi Kathiravan</span></strong><br>';
echo 'Position: Pro-Chancellor<br>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="committee-section">';
echo '<h2 class="chief-patrons-title">Committee Members</h2>';
echo '';
echo '<!-- Conference Advisors -->';
echo '<div class="committee-category">';
echo '<h3>Conference Advisors</h3>';
echo '<div class="team-section">';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. Dhanasekaran Devaraj</strong>';
echo '<p>Registrar, DSU</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. J. Mathana</strong>';
echo '<p>Dean Academics, DSU</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Mr. S. Divesh</strong>';
echo '<p>Dean Approvals, DSU</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Technical Advisors -->';
echo '<div class="committee-category">';
echo '<h3>Technical Advisors</h3>';
echo '<div class="team-section">';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. A. Thulasi</strong>';
echo '<p>Dean, SMCH, DSU</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. Shankar Duraikannan</strong>';
echo '<p>Dean, SET, DSU</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. K. Rekha</strong>';
echo '<p>Associate Dean, SAHS, DSU</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. K. Chozhan</strong>';
echo '<p>Dean, SAS, DSU</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. J. Ramesh Kumar</strong>';
echo '<p>Dean, Physiotherapy, DSU</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. J. Sathiyapriya</strong>';
echo '<p>Dean, Nursing, DSU</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. S. Akilandeswari</strong>';
echo '<p>Dean, SOP, DSU</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Ar.P. Jeyaprakash</strong>';
echo '<p>Dean, SOA, DSU</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. Anandavel</strong>';
echo '<p>Associate Dean, SOM, DSU</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. B. Rajeswari</strong>';
echo '<p>Dean, SOL, DSU</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Conference Chair -->';
echo '<div class="committee-category">';
echo '<h3>Conference Chair</h3>';
echo '<div class="team-section">';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. N. Shanmugapriya</strong>';
echo '<p>HoD, AI&DS, SET, DSU</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Conference Co-Chair -->';
echo '<div class="committee-category">';
echo '<h3>Conference Co-Chair</h3>';
echo '<div class="team-section">';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. B. Shanmugham</strong>';
echo '<p>HoD, BME, SET, DSU</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Finance and Sponsorship Chair -->';
echo '<div class="committee-category">';
echo '<h3>Finance and Sponsorship Chair</h3>';
echo '<div class="team-section">';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. N. Shankar</strong>';
echo '<p>Assoc. Prof., SET, DSU</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. M. Sughasiny</strong>';
echo '<p>HoD, MCA, SET, DSU</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Thematic Track Advisors -->';
echo '<div class="committee-category">';
echo '<h3>Thematic Track Advisors</h3>';
echo '<div class="team-section">';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. V. Raju</strong>';
echo '<p>Assoc. Dean, SET, DSU</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. G. Sasikumar</strong>';
echo '<p>Assoc. Dean, SET, DSU</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. B. Ramesh</strong>';
echo '<p>Assoc. Dean, SET, DSU</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Publication & Publicity Chair -->';
echo '<div class="committee-category">';
echo '<h3>Publication & Publicity Chair</h3>';
echo '<div class="team-section">';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. R. Ramkumar</strong>';
echo '<p>Assoc. Prof., SET, DSU</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. P. Rajiniganth</strong>';
echo '<p>Assoc. Prof., SET, DSU</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<!-- Organising and Technical Committee Chairs -->';
echo '<div class="committee-category">';
echo '<h3>Organising and Technical Committee Chairs</h3>';
echo '<div class="team-section">';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Mr. S. Bharath</strong>';
echo '<p>HoD, Agriculture Engineering</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. V. L. Maruthanila</strong>';
echo '<p>HoD, BioTech</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '<div class="text-container">';
echo '<strong>Dr. J. Mercy Geraldine</strong>';
echo '<p>HoD, CSE</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. N. Sundararajulu</strong>';
echo '<p>HoD, Cyber Security</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. N. Kumaran</strong>';
echo '<p>HoD, IoT</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. P. Geetha</strong>';
echo '<p>HoD, ECE</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. M. Lakshmi</strong>';
echo '<p>HoD, EEE</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. S. Padmapriya</strong>';
echo '<p>HoD, IT</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. T. Sathis Kumar</strong>';
echo '<p>HoD, AIML</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. G.M. Balamurugan</strong>';
echo '<p>HoD, MECH</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. R. Shobia</strong>';
echo '<p>HoD, English</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. Sharad Porwal</strong>';
echo '<p>HoD, Chemistry</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. R. Sathiyapriya</strong>';
echo '<p>HoD, Mathematics</p>';
echo '</div>';
echo '</div>';
echo '<div class="committee-member">';
echo '';
echo '<div class="text-container">';
echo '<strong>Dr. S. Rafi Ahamed</strong>';
echo '<p>HoD, Physics</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '';
echo '<section id="accomadation">';
echo '<div class="faq-section">';
echo '<center> <h2>Accommodation and Nearby Places</h2></center>';
echo '<center><h4>Here are some accommodation options and nearby places to visit for the attendees of the MSET2025 conference:</h4></center>';
echo '<div class="dropdown-item">';
echo '<input type="checkbox" id="accommodation-toggle-1" class="dropdown-toggle">';
echo '<label for="accommodation-toggle-1" class="dropdown-button">Accommodation Options <span class="arrow">&#9660;</span></label>';
echo '<div class="dropdown-content">';
echo '<ul>';
echo '<li class="flex-container">';
echo '<div class="text-container">';
echo '<strong>Grand Gardenia</strong><br>';
echo 'Rating: 3-star<br>';
echo 'Description: Centrally located with free Wi-Fi, fitness center, and two restaurants serving Chinese, South Indian, and rooftop Golden Palm cuisine.<br>';
echo 'Contact: +91 4312 222222<br>';
echo 'Price: ₹2,800 - ₹4,500 per night<br>';
echo '</div>';
echo '<img src="https://res.cloudinary.com/simplotel/image/upload/x_0,y_67,w_1280,h_719,r_0,c_crop,q_80,fl_progressive/w_455,f_auto,c_fit/grand-gardenia-tiruchirappalli/IMG-20210330-WA0001_mdfzf2" alt="Grand Gardenia" class ="image-container">';
echo '</li>';
echo '<li class="flex-container">';
echo '<div class="text-container">';
echo '<strong>KVM Hotels</strong><br>';
echo 'Rating: 3-star<br>';
echo 'Description: Offers comfortable rooms and essential amenities with courteous staff.<br>';
echo 'Contact: +91 4312 333333<br>';
echo 'Price: ₹2,500 - ₹3,500 per night<br>';
echo '</div>';
echo '<img src="https://th.bing.com/th/id/R.9183a229cc18aa8cf2470313a0f611fb?rik=UTRqAR5o1EYHNA&riu=http%3a%2f%2fkvmhotels.com%2fapps%2fimages%2fgallery_images%2f1.jpg&ehk=lZWwmuTeB8uxeXBpiVubzDsHaOSVs0G%2fhxu%2fTpbvPhs%3d&risl=&pid=ImgRaw&r=0" alt="KVM Hotels" class="image-container">';
echo '</li>';
echo '<li class="flex-container">';
echo '<div class="text-container">';
echo '<strong>Hotel Le Temps Fort</strong><br>';
echo 'Rating: 4-star<br>';
echo 'Description: Offers luxury accommodation with premium amenities.<br>';
echo 'Contact: +91 94433 12345<br>';
echo 'Price: ₹3,500 - ₹6,000 per night<br>';
echo '</div>';
echo '<img src="https://pbs.twimg.com/media/ClN4dz3UkAAsx5s.jpg" alt="Hotel Le Temps Fort" class="image-container">';
echo '</li>';
echo '<li class="flex-container">';
echo '<div class="text-container">';
echo '<strong>Red Fox Hotel</strong><br>';
echo 'Rating: 3-star<br>';
echo 'Description: Budget-friendly hotel with modern amenities.<br>';
echo 'Contact: +91 89256 78798<br>';
echo 'Price: ₹2,299 - ₹3,500 per night<br>';
echo '</div>';
echo '<img src="https://dynamic-media-cdn.tripadvisor.com/media/photo-o/29/4d/15/63/caption.jpg?w=500&h=-1&s=1" alt="Red Fox Hotel" class="image-container">';
echo '</li>';
echo '<li class="flex-container">';
echo '<div class="text-container">';
echo '<strong>SRM Hotel</strong><br>';
echo 'Rating: 3-star<br>';
echo 'Description: Provides a comfortable stay with good amenities.<br>';
echo 'Contact: +91 431 2255 100<br>';
echo 'Price: ₹3,300 - ₹4,000 per night<br>';
echo '</div>';
echo '<img src="https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/44/b3/bd/business-class-twin-bed.jpg?w=700&h=-1&s=1" alt="SRM Hotel" class="image-container">';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="dropdown-item">';
echo '<input type="checkbox" id="places-toggle-2" class="dropdown-toggle">';
echo '<label for="places-toggle-2" class="dropdown-button">Nearby Places to Visit <span class="arrow">&#9660;</span></label>';
echo '<div class="dropdown-content">';
echo '<ul>';
echo '<li class="flex-container">';
echo '<div class="text-container">';
echo '<strong>Rockfort Temple</strong><br>';
echo 'Description: A historic fort and temple complex perched on a massive rock, offering panoramic views of the city.<br>';
echo 'Distance: 12 km from Dhanalakshmi Srinivasan University<br>';
echo '</div>';
echo '<img src="https://th.bing.com/th/id/R.487aa124d97cc97348f6e66d1f37f64b?rik=iRE9R3t%2fYLzQ3A&riu=http%3a%2f%2fblog.lemontreehotels.com%2fwp-content%2fuploads%2f2019%2f03%2fRockfort-Temple-Trichy.jpg&ehk=l%2bxP7rU5rdlarN4g7AO8LBjfdEQyMQlFd90GEZKUOgk%3d&risl=&pid=ImgRaw&r=0&sres=1&sresct=1" alt="Rockfort Temple" class="image-container">';
echo '</li>';
echo '<li class="flex-container">';
echo '<div class="text-container">';
echo '<strong>Sri Ranganathaswamy Temple</strong><br>';
echo 'Description: One of the largest and most important Vaishnavite shrines in India, known for its stunning architecture.<br>';
echo 'Distance: 15 km from Dhanalakshmi Srinivasan University<br>';
echo '</div>';
echo '<img src="https://i.pinimg.com/originals/09/8a/be/098abea8b8cd8bcc519f8f05d2bc9f85.jpg" alt="Sri Ranganathaswamy Temple" class="image-container">';
echo '</li>';
echo '<li class="flex-container">';
echo '<div class="text-container">';
echo '<strong>Jambukeswarar Temple</strong><br>';
echo 'Description: An ancient temple dedicated to Lord Shiva, featuring intricate carvings and a sacred water tank.<br>';
echo 'Distance: 14 km from Dhanalakshmi Srinivasan University<br>';
echo '</div>';
echo '<img src="https://1.bp.blogspot.com/-czd1OAHx34E/WI4OeJE5xII/AAAAAAAAFoU/R7F3v3HkVB8DEzWsmUrJNgpo2Di1XZS5gCLcB/s1600/srirangam%2Btemple%2Btower.jpg" alt="Jambukeswarar Temple" class="image-container">';
echo '</li>';
echo '<li class="flex-container">';
echo '<div class="text-container">';
echo '<strong>St. Joseph's Church</strong><br>';
echo 'Description: A beautiful colonial-era church known for its serene atmosphere and impressive architecture.<br>';
echo 'Distance: 13 km from Dhanalakshmi Srinivasan University<br>';
echo '</div>';
echo '<img src="https://lh4.googleusercontent.com/-aW0xJofGGPo/TXzVny6EVEI/AAAAAAAAAL4/Gie-SbwnHnQ/s1600/stosephtrichy.jpg" alt="St. Joseph's Church" class="image-container">';
echo '</li>';
echo '<li class="flex-container">';
echo '<div class="text-container">';
echo '<strong>Kallanai Dam</strong><br>';
echo 'Description: One of the oldest water diversion structures in the world, built across the Kaveri River.<br>';
echo 'Distance: 25 km from Dhanalakshmi Srinivasan University<br>';
echo '</div>';
echo '<img src="https://th.bing.com/th/id/OIP.GH3suf3YhPovR57GnUVAQwHaFj?rs=1&pid=ImgDetMain" alt="Kallanai Dam" class="image-container">';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="faq-section">';
echo '<center> <h2>FAQ's</h2></center>';
echo '<div class="dropdown-item">';
echo '<input type="checkbox" id="faq-toggle-1" class="dropdown-toggle">';
echo '<label for="faq-toggle-1" class="dropdown-button">How do I register for the MSET2025 conference? <span class="arrow">&#9660;</span></label>';
echo '<div class="dropdown-content">';
echo '<p>You can register for the MSET2025 conference by visiting our official registration page on the conference website. Fill out the required information and complete the payment process to secure your spot.</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="dropdown-item">';
echo '<input type="checkbox" id="faq-toggle-2" class="dropdown-toggle">';
echo '<label for="faq-toggle-2" class="dropdown-button">What is the registration deadline? <span class="arrow">&#9660;</span></label>';
echo '<div class="dropdown-content">';
echo '<p>The registration deadline for the MSET2025 conference is February 28, 2025. Please make sure to register before this date to ensure your participation.</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="dropdown-item">';
echo '<input type="checkbox" id="faq-toggle-3" class="dropdown-toggle">';
echo '<label for="faq-toggle-3" class="dropdown-button"> Where will the conference be held?<span class="arrow">&#9660;</span></label>';
echo '<div class="dropdown-content">';
echo '<p>The MSET2025 conference will be held at Dhanalakshmi Srinivasan University, Tiruchirappalli, Tamil Nadu, India.</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="dropdown-item">';
echo '<input type="checkbox" id="faq-toggle-4" class="dropdown-toggle">';
echo '<label for="faq-toggle-4" class="dropdown-button">Can I submit an abstract for presentation? <span class="arrow">&#9660;</span></label>';
echo '<div class="dropdown-content">';
echo '<p>Yes, abstract submissions are welcome for the MSET2025 conference. The deadline for abstract submission is February 28, 2025. Please visit the conference website for guidelines and submission details.</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="dropdown-item">';
echo '<input type="checkbox" id="faq-toggle-5" class="dropdown-toggle">';
echo '<label for="faq-toggle-5" class="dropdown-button">Are there any networking opportunities at the conference? <span class="arrow">&#9660;</span></label>';
echo '<div class="dropdown-content">';
echo '<p>Yes, the MSET2025 conference will provide various networking opportunities, including panel discussions, workshops, and social events where attendees can engage with experts, peers, and professionals from around the world.</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="dropdown-item">';
echo '<input type="checkbox" id="faq-toggle-6" class="dropdown-toggle">';
echo '<label for="faq-toggle-6" class="dropdown-button"> What accommodation options are available for attendees?<span class="arrow">&#9660;</span></label>';
echo '<div class="dropdown-content">';
echo '<p>There are several accommodation options available near Dhanalakshmi Srinivasan University. We recommend booking your accommodation early to ensure availability. Please refer to the accommodation page on the conference website for more information.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '';
echo '<footer>';
echo '<div class="footer-container">';
echo '<div class="footer-section">';
echo '<div class="footer-left">';
echo '<img src="/assests/dsu.png" alt="University Logo" class="university-logo">';
echo '<div class="university-name">';
echo '<span>Dhanalakshmi Srinivasan</span>';
echo '<span>University</span>';
echo '</div>';
echo '</div>';
echo '<form method='POST' name='contact'><input type='hidden' name='form-name' value='contact' />';
echo '';
echo '';
echo '<div class="newsletter">';
echo '<p>';
echo '<label>Your Name: <input type="text" name="name" /></label>';
echo '</p>';
echo '<br>';
echo '<p>';
echo '<label>Your Email: <input type="email" name="email" /></label>';
echo '</p>';
echo '<p>';
echo '<button type="submit">&#10140;</button>';
echo '</p>';
echo '</div>';
echo '</form>';
echo '<div class="social-icons">';
echo '<img src="/assests/twitter.png" alt="Twitter">';
echo '<img src="/assests/insta.png" alt="WhatsApp">';
echo '<img src="/assests/fb.png" alt="Instagram">';
echo '<img src="/assests/whatsapp.png" alt="Facebook">';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="footer-links">';
echo '<div class="links-section">';
echo '<h4>Updates</h4>';
echo '<ul>';
echo '<li>Registration</li>';
echo '<li>Submission</li>';
echo '<li>Key dates</li>';
echo '<li>Call for conformation</li>';
echo '<li>Team</li>';
echo '<li>Career</li>';
echo '</ul>';
echo '</div>';
echo '<div class="links-section">';
echo '<h4>Important Links</h4>';
echo '<ul>';
echo '<li>MSET 2025</li>';
echo '<li>Sponsors</li>';
echo '<li>Venue Info</li>';
echo '';
echo '<li>Join the day</li>';
echo '<li>FAQ</li>';
echo '</ul>';
echo '</div>';
echo '<div class="links-section">';
echo '<h4>Gallery</h4>';
echo '<ul>';
echo '<li>Upcoming events</li>';
echo '<li>Past Events</li>';
echo '<li><a href='/gallery'>Gallery</a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="footer-right">';
echo '<img src="/assests/school.png" alt="School of Engineering Logo" class="school-logo">';
echo '<h3>School of <br> Engineering and Technology</h3>';
echo '<img src="/assests/logo copy.png" alt="Gallery Icon" class="gallery-icon">';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="footer-bottom">';
echo '<p>© studentdevelopercommunity. All Rights Reserved 2025</p>';
echo '<p>Designed by Divya | VK';
echo '</p>';
echo '<a href="#">Terms & Conditions</a>';
echo '</div>';
echo '</footer>';
echo '</body>';
echo '';
echo '<script src="/script.js"></script>';
echo '</html>';
echo '';
?>